"""添加张三字段

Revision ID: 5ac10ab42c29
Revises: 18e3b2701a47
Create Date: 2022-02-08 23:22:33.406380

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5ac10ab42c29'
down_revision = '18e3b2701a47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pity_database_info', 'zhangsan')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pity_database_info', sa.Column('zhangsan', mysql.VARCHAR(length=12), nullable=True))
    # ### end Alembic commands ###
