"""test

Revision ID: 5d3fd76680f4
Revises: 
Create Date: 2022-07-22 10:58:44.705487

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5d3fd76680f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pity_broadcast_read_user',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('notification_id', sa.INTEGER(), nullable=True, comment='对应消息id'),
    sa.Column('read_user', sa.INTEGER(), nullable=True, comment='已读用户id'),
    sa.Column('read_time', sa.TIMESTAMP(), nullable=True, comment='已读时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pity_broadcast_read_user_notification_id'), 'pity_broadcast_read_user', ['notification_id'], unique=False)
    op.create_table('pity_constructor',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('deleted_at', sa.BIGINT(), nullable=False),
    sa.Column('create_user', sa.INTEGER(), nullable=False),
    sa.Column('update_user', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.INTEGER(), nullable=True, comment='0: testcase 1: sql 2: redis 3: py脚本 4: 其它'),
    sa.Column('name', sa.String(length=64), nullable=True, comment='数据初始化描述'),
    sa.Column('enable', sa.BOOLEAN(), nullable=False),
    sa.Column('constructor_json', sa.TEXT(), nullable=False),
    sa.Column('value', sa.String(length=16), nullable=True, comment='返回值'),
    sa.Column('case_id', sa.INTEGER(), nullable=False, comment='所属用例id'),
    sa.Column('public', sa.BOOLEAN(), nullable=True, comment='是否共享'),
    sa.Column('index', sa.INTEGER(), nullable=True, comment='前置条件顺序'),
    sa.Column('suffix', sa.BOOLEAN(), nullable=True, comment='是否是后置条件，默认为否'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'suffix', 'name', 'deleted_at')
    )
    op.create_table('pity_database_info',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('deleted_at', sa.BIGINT(), nullable=False),
    sa.Column('create_user', sa.INTEGER(), nullable=False),
    sa.Column('update_user', sa.INTEGER(), nullable=False),
    sa.Column('env', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(length=24), nullable=False),
    sa.Column('host', sa.String(length=64), nullable=False),
    sa.Column('port', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.String(length=36), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('database', sa.String(length=36), nullable=False),
    sa.Column('sql_type', sa.INTEGER(), nullable=False, comment='0: mysql 1: postgresql 2: mongo'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('env', 'name', 'deleted_at')
    )
    op.create_table('pity_environment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('deleted_at', sa.BIGINT(), nullable=False),
    sa.Column('create_user', sa.INTEGER(), nullable=False),
    sa.Column('update_user', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=True),
    sa.Column('remarks', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'deleted_at')
    )
    op.create_table('pity_gateway',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('deleted_at', sa.BIGINT(), nullable=False),
    sa.Column('create_user', sa.INTEGER(), nullable=False),
    sa.Column('update_user', sa.INTEGER(), nullable=False),
    sa.Column('env', sa.INTEGER(), nullable=True, comment='对应环境'),
    sa.Column('name', sa.String(length=32), nullable=True, comment='网关名称'),
    sa.Column('gateway', sa.String(length=128), nullable=True, comment='网关地址'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('env', 'name', 'deleted_at')
    )
    op.create_table('pity_gconfig',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('deleted_at', sa.BIGINT(), nullable=False),
    sa.Column('create_user', sa.INTEGER(), nullable=False),
    sa.Column('update_user', sa.INTEGER(), nullable=False),
    sa.Column('env', sa.INTEGER(), nullable=True),
    sa.Column('key', sa.String(length=16), nullable=True),
    sa.Column('value', sa.TEXT(), nullable=True),
    sa.Column('key_type', sa.INTEGER(), nullable=False, comment='0: string 1: json 2: yaml'),
    sa.Column('enable', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('env', 'key', 'deleted_at')
    )
    op.create_table('pity_notification',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('deleted_at', sa.BIGINT(), nullable=False),
    sa.Column('create_user', sa.INTEGER(), nullable=False),
    sa.Column('update_user', sa.INTEGER(), nullable=False),
    sa.Column('msg_type', sa.SMALLINT(), nullable=True, comment='消息类型 1: 系统消息 2: 其他消息'),
    sa.Column('msg_title', sa.VARCHAR(length=32), nullable=False, comment='消息标题'),
    sa.Column('msg_content', sa.VARCHAR(length=200), nullable=True, comment='消息内容'),
    sa.Column('msg_link', sa.VARCHAR(length=128), nullable=True, comment='消息链接'),
    sa.Column('msg_status', sa.SMALLINT(), nullable=True, comment='消息状态 1: 未读 2: 已读'),
    sa.Column('sender', sa.INTEGER(), nullable=True, comment='消息发送人, 0则是CPU 非0则是其他用户'),
    sa.Column('receiver', sa.INTEGER(), nullable=True, comment='消息接收人, 系统消息则该字段为空'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pity_operation_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('operate_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True, comment='操作描述'),
    sa.Column('tag', sa.String(length=24), nullable=True, comment='操作tag'),
    sa.Column('mode', sa.SMALLINT(), nullable=True, comment='操作类型'),
    sa.Column('key', sa.INTEGER(), nullable=True, comment='关键id，可能是目录id，case_id或者其他id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pity_operation_log_user_id'), 'pity_operation_log', ['user_id'], unique=False)
    op.create_table('pity_oss_file',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('deleted_at', sa.BIGINT(), nullable=False),
    sa.Column('create_user', sa.INTEGER(), nullable=False),
    sa.Column('update_user', sa.INTEGER(), nullable=False),
    sa.Column('file_path', sa.String(length=64), nullable=False, comment='文件路径'),
    sa.Column('view_url', sa.String(length=256), nullable=False, comment='文件预览url'),
    sa.Column('file_size', sa.String(length=16), nullable=True, comment='文件大小'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path', 'deleted_at')
    )
    op.create_index(op.f('ix_pity_oss_file_file_path'), 'pity_oss_file', ['file_path'], unique=False)
    op.create_table('pity_out_parameters',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('deleted_at', sa.BIGINT(), nullable=False),
    sa.Column('create_user', sa.INTEGER(), nullable=False),
    sa.Column('update_user', sa.INTEGER(), nullable=False),
    sa.Column('case_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(length=24), nullable=False),
    sa.Column('source', sa.INTEGER(), nullable=False, comment='0: Body(TEXT) 1: Body(JSON) 2: Header 3: Cookie 4: HTTP状态码'),
    sa.Column('expression', sa.String(length=128), nullable=True),
    sa.Column('match_index', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'name', 'deleted_at')
    )
    op.create_table('pity_project',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('deleted_at', sa.BIGINT(), nullable=False),
    sa.Column('create_user', sa.INTEGER(), nullable=False),
    sa.Column('update_user', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=True),
    sa.Column('owner', sa.INTEGER(), nullable=True),
    sa.Column('app', sa.String(length=32), nullable=True),
    sa.Column('private', sa.BOOLEAN(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('avatar', sa.String(length=128), nullable=True),
    sa.Column('dingtalk_url', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pity_project_app'), 'pity_project', ['app'], unique=False)
    op.create_index(op.f('ix_pity_project_name'), 'pity_project', ['name'], unique=True)
    op.create_table('pity_project_role',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('deleted_at', sa.BIGINT(), nullable=False),
    sa.Column('create_user', sa.INTEGER(), nullable=False),
    sa.Column('update_user', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('project_id', sa.INTEGER(), nullable=True),
    sa.Column('project_role', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pity_project_role_project_id'), 'pity_project_role', ['project_id'], unique=False)
    op.create_index(op.f('ix_pity_project_role_project_role'), 'pity_project_role', ['project_role'], unique=False)
    op.create_index(op.f('ix_pity_project_role_user_id'), 'pity_project_role', ['user_id'], unique=False)
    op.create_table('pity_redis_info',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('deleted_at', sa.BIGINT(), nullable=False),
    sa.Column('create_user', sa.INTEGER(), nullable=False),
    sa.Column('update_user', sa.INTEGER(), nullable=False),
    sa.Column('env', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(length=24), nullable=False),
    sa.Column('addr', sa.String(length=128), nullable=False),
    sa.Column('username', sa.String(length=36), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('db', sa.INTEGER(), nullable=False),
    sa.Column('cluster', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('env', 'name', 'deleted_at')
    )
    op.create_table('pity_report',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('executor', sa.INTEGER(), nullable=True),
    sa.Column('env', sa.INTEGER(), nullable=False),
    sa.Column('cost', sa.String(length=8), nullable=True),
    sa.Column('plan_id', sa.INTEGER(), nullable=True),
    sa.Column('start_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('finished_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('success_count', sa.INTEGER(), nullable=False),
    sa.Column('error_count', sa.INTEGER(), nullable=False),
    sa.Column('failed_count', sa.INTEGER(), nullable=False),
    sa.Column('skipped_count', sa.INTEGER(), nullable=False),
    sa.Column('status', mysql.SMALLINT(), nullable=False, comment='0: pending, 1: running, 2: stopped, 3: finished'),
    sa.Column('mode', mysql.SMALLINT(), nullable=True, comment='0: 普通, 1: 测试集, 2: pipeline, 3: 其他'),
    sa.Column('deleted_at', sa.BIGINT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pity_report_executor'), 'pity_report', ['executor'], unique=False)
    op.create_index(op.f('ix_pity_report_plan_id'), 'pity_report', ['plan_id'], unique=False)
    op.create_index(op.f('ix_pity_report_status'), 'pity_report', ['status'], unique=False)
    op.create_table('pity_test_plan',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('deleted_at', sa.BIGINT(), nullable=False),
    sa.Column('create_user', sa.INTEGER(), nullable=False),
    sa.Column('update_user', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('env', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=3), nullable=False),
    sa.Column('cron', sa.String(length=24), nullable=False),
    sa.Column('case_list', sa.TEXT(), nullable=False),
    sa.Column('ordered', sa.BOOLEAN(), nullable=True),
    sa.Column('pass_rate', sa.SMALLINT(), nullable=True),
    sa.Column('receiver', sa.TEXT(), nullable=True),
    sa.Column('msg_type', sa.TEXT(), nullable=True),
    sa.Column('retry_minutes', sa.SMALLINT(), nullable=False),
    sa.Column('state', sa.SMALLINT(), nullable=True, comment='0: 未开始 1: 运行中'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', 'deleted_at')
    )
    op.create_table('pity_test_result',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('report_id', sa.INTEGER(), nullable=True),
    sa.Column('case_id', sa.INTEGER(), nullable=True),
    sa.Column('case_name', sa.String(length=32), nullable=True),
    sa.Column('status', sa.SMALLINT(), nullable=True, comment='对应状态 0: 成功 1: 失败 2: 出错 3: 跳过'),
    sa.Column('start_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('finished_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('case_log', sa.TEXT(), nullable=True),
    sa.Column('retry', sa.INTEGER(), nullable=True),
    sa.Column('status_code', sa.INTEGER(), nullable=True),
    sa.Column('url', sa.TEXT(), nullable=True),
    sa.Column('body', sa.TEXT(), nullable=True),
    sa.Column('request_params', sa.TEXT(), nullable=True),
    sa.Column('data_name', sa.String(length=24), nullable=True),
    sa.Column('data_id', sa.INTEGER(), nullable=True),
    sa.Column('request_method', sa.String(length=12), nullable=True),
    sa.Column('request_headers', sa.TEXT(), nullable=True),
    sa.Column('cost', sa.String(length=12), nullable=False),
    sa.Column('asserts', sa.TEXT(), nullable=True),
    sa.Column('response_headers', sa.TEXT(), nullable=True),
    sa.Column('response', sa.TEXT(), nullable=True),
    sa.Column('cookies', sa.TEXT(), nullable=True),
    sa.Column('deleted_at', sa.BIGINT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pity_test_result_case_id'), 'pity_test_result', ['case_id'], unique=False)
    op.create_index(op.f('ix_pity_test_result_report_id'), 'pity_test_result', ['report_id'], unique=False)
    op.create_table('pity_testcase',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('deleted_at', sa.BIGINT(), nullable=False),
    sa.Column('create_user', sa.INTEGER(), nullable=False),
    sa.Column('update_user', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('request_type', sa.INTEGER(), nullable=True, comment='请求类型 1: http 2: grpc 3: dubbo'),
    sa.Column('url', sa.TEXT(), nullable=False, comment='请求url'),
    sa.Column('request_method', sa.String(length=12), nullable=True, comment='请求方式, 如果非http可为空'),
    sa.Column('request_headers', sa.TEXT(), nullable=True, comment='请求头，可为空'),
    sa.Column('base_path', sa.String(length=24), nullable=True, comment='请求base_path'),
    sa.Column('body', sa.TEXT(), nullable=True, comment='请求body'),
    sa.Column('body_type', sa.INTEGER(), nullable=True, comment='请求类型, 0: none 1: json 2: form 3: x-form 4: binary 5: GraphQL'),
    sa.Column('directory_id', sa.INTEGER(), nullable=True, comment='所属目录'),
    sa.Column('tag', sa.String(length=64), nullable=True, comment='用例标签'),
    sa.Column('status', sa.INTEGER(), nullable=True, comment='用例状态: 1: 调试中 2: 暂时关闭 3: 正常运作'),
    sa.Column('priority', sa.String(length=3), nullable=True, comment='用例优先级: p0-p3'),
    sa.Column('case_type', sa.SMALLINT(), nullable=True, comment='0: 普通用例 1: 前置用例 2: 数据工厂'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('directory_id', 'name', 'deleted_at')
    )
    op.create_index(op.f('ix_pity_testcase_name'), 'pity_testcase', ['name'], unique=False)
    op.create_table('pity_testcase_asserts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('deleted_at', sa.BIGINT(), nullable=False),
    sa.Column('create_user', sa.INTEGER(), nullable=False),
    sa.Column('update_user', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('case_id', sa.INTEGER(), nullable=True),
    sa.Column('assert_type', sa.String(length=16), nullable=True, comment='equal: 等于 not_equal: 不等于 in: 属于'),
    sa.Column('expected', sa.TEXT(), nullable=False),
    sa.Column('actually', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pity_testcase_asserts_case_id'), 'pity_testcase_asserts', ['case_id'], unique=False)
    op.create_table('pity_testcase_data',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('deleted_at', sa.BIGINT(), nullable=False),
    sa.Column('create_user', sa.INTEGER(), nullable=False),
    sa.Column('update_user', sa.INTEGER(), nullable=False),
    sa.Column('env', sa.INTEGER(), nullable=False),
    sa.Column('case_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('json_data', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('env', 'case_id', 'name', 'deleted_at')
    )
    op.create_table('pity_testcase_directory',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('deleted_at', sa.BIGINT(), nullable=False),
    sa.Column('create_user', sa.INTEGER(), nullable=False),
    sa.Column('update_user', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.String(length=18), nullable=False),
    sa.Column('parent', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', 'parent', 'deleted_at')
    )
    op.create_index(op.f('ix_pity_testcase_directory_project_id'), 'pity_testcase_directory', ['project_id'], unique=False)
    op.create_table('pity_testplan_follow_user_rel',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('deleted_at', sa.BIGINT(), nullable=False),
    sa.Column('create_user', sa.INTEGER(), nullable=False),
    sa.Column('update_user', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('plan_id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'plan_id', 'deleted_at')
    )
    op.create_table('pity_user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.String(length=16), nullable=True),
    sa.Column('name', sa.String(length=16), nullable=True),
    sa.Column('password', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('role', sa.INTEGER(), nullable=True, comment='0: 普通用户 1: 组长 2: 超级管理员'),
    sa.Column('phone', sa.String(length=12), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('deleted_at', sa.BIGINT(), nullable=False),
    sa.Column('update_user', sa.INTEGER(), nullable=True),
    sa.Column('last_login_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('avatar', sa.String(length=128), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False, comment='是否合法'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_pity_user_name'), 'pity_user', ['name'], unique=False)
    op.create_index(op.f('ix_pity_user_username'), 'pity_user', ['username'], unique=True)
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apscheduler_jobs',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('next_run_time', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('job_state', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    op.drop_index(op.f('ix_pity_user_username'), table_name='pity_user')
    op.drop_index(op.f('ix_pity_user_name'), table_name='pity_user')
    op.drop_table('pity_user')
    op.drop_table('pity_testplan_follow_user_rel')
    op.drop_index(op.f('ix_pity_testcase_directory_project_id'), table_name='pity_testcase_directory')
    op.drop_table('pity_testcase_directory')
    op.drop_table('pity_testcase_data')
    op.drop_index(op.f('ix_pity_testcase_asserts_case_id'), table_name='pity_testcase_asserts')
    op.drop_table('pity_testcase_asserts')
    op.drop_index(op.f('ix_pity_testcase_name'), table_name='pity_testcase')
    op.drop_table('pity_testcase')
    op.drop_index(op.f('ix_pity_test_result_report_id'), table_name='pity_test_result')
    op.drop_index(op.f('ix_pity_test_result_case_id'), table_name='pity_test_result')
    op.drop_table('pity_test_result')
    op.drop_table('pity_test_plan')
    op.drop_index(op.f('ix_pity_report_status'), table_name='pity_report')
    op.drop_index(op.f('ix_pity_report_plan_id'), table_name='pity_report')
    op.drop_index(op.f('ix_pity_report_executor'), table_name='pity_report')
    op.drop_table('pity_report')
    op.drop_table('pity_redis_info')
    op.drop_index(op.f('ix_pity_project_role_user_id'), table_name='pity_project_role')
    op.drop_index(op.f('ix_pity_project_role_project_role'), table_name='pity_project_role')
    op.drop_index(op.f('ix_pity_project_role_project_id'), table_name='pity_project_role')
    op.drop_table('pity_project_role')
    op.drop_index(op.f('ix_pity_project_name'), table_name='pity_project')
    op.drop_index(op.f('ix_pity_project_app'), table_name='pity_project')
    op.drop_table('pity_project')
    op.drop_table('pity_out_parameters')
    op.drop_index(op.f('ix_pity_oss_file_file_path'), table_name='pity_oss_file')
    op.drop_table('pity_oss_file')
    op.drop_index(op.f('ix_pity_operation_log_user_id'), table_name='pity_operation_log')
    op.drop_table('pity_operation_log')
    op.drop_table('pity_notification')
    op.drop_table('pity_gconfig')
    op.drop_table('pity_gateway')
    op.drop_table('pity_environment')
    op.drop_table('pity_database_info')
    op.drop_table('pity_constructor')
    op.drop_index(op.f('ix_pity_broadcast_read_user_notification_id'), table_name='pity_broadcast_read_user')
    op.drop_table('pity_broadcast_read_user')
    # ### end Alembic commands ###
