# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import app.v1.service.request_pb2 as request__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x1a\rrequest.proto2\xc4\x03\n\x04user\x12,\n\x05login\x12\x0f.app.v1.Request\x1a\x10.app.v1.Response\"\x00\x12/\n\x08listUser\x12\x0f.app.v1.Request\x1a\x10.app.v1.Response\"\x00\x12/\n\x08register\x12\x0f.app.v1.Request\x1a\x10.app.v1.Response\"\x00\x12-\n\x06\x64\x65lete\x12\x0f.app.v1.Request\x1a\x10.app.v1.Response\"\x00\x12\x34\n\rresetPassword\x12\x0f.app.v1.Request\x1a\x10.app.v1.Response\"\x00\x12-\n\x06update\x12\x0f.app.v1.Request\x1a\x10.app.v1.Response\"\x00\x12\x37\n\x10generatePassword\x12\x0f.app.v1.Request\x1a\x10.app.v1.Response\"\x00\x12\x31\n\ncheckToken\x12\x0f.app.v1.Request\x1a\x10.app.v1.Response\"\x00\x12,\n\x05query\x12\x0f.app.v1.Request\x1a\x10.app.v1.Response\"\x00\x62\x06proto3')



_USER = DESCRIPTOR.services_by_name['user']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USER._serialized_start=30
  _USER._serialized_end=482
# @@protoc_insertion_point(module_scope)
