# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import app.v1.request_pb2 as request__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x1a\rrequest.proto\"5\n\x0fLoginRequestDto\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\t\n\x07UserDto\"J\n\x10LoginResponseDto\x12\x16\n\x04user\x18\x01 \x01(\x0b\x32\x08.UserDto\x12\r\n\x05token\x18\x02 \x01(\t\x12\x0f\n\x07\x65xpired\x18\x03 \x01(\x03\x32\x96\x01\n\x04user\x12,\n\x05login\x12\x0f.app.v1.Request\x1a\x10.app.v1.Response\"\x00\x12/\n\x08listUser\x12\x0f.app.v1.Request\x1a\x10.app.v1.Response\"\x00\x12/\n\x08register\x12\x0f.app.v1.Request\x1a\x10.app.v1.Response\"\x00\x62\x06proto3')



_LOGINREQUESTDTO = DESCRIPTOR.message_types_by_name['LoginRequestDto']
_USERDTO = DESCRIPTOR.message_types_by_name['UserDto']
_LOGINRESPONSEDTO = DESCRIPTOR.message_types_by_name['LoginResponseDto']
LoginRequestDto = _reflection.GeneratedProtocolMessageType('LoginRequestDto', (_message.Message,), {
  'DESCRIPTOR' : _LOGINREQUESTDTO,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:LoginRequestDto)
  })
_sym_db.RegisterMessage(LoginRequestDto)

UserDto = _reflection.GeneratedProtocolMessageType('UserDto', (_message.Message,), {
  'DESCRIPTOR' : _USERDTO,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:UserDto)
  })
_sym_db.RegisterMessage(UserDto)

LoginResponseDto = _reflection.GeneratedProtocolMessageType('LoginResponseDto', (_message.Message,), {
  'DESCRIPTOR' : _LOGINRESPONSEDTO,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:LoginResponseDto)
  })
_sym_db.RegisterMessage(LoginResponseDto)

_USER = DESCRIPTOR.services_by_name['user']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOGINREQUESTDTO._serialized_start=29
  _LOGINREQUESTDTO._serialized_end=82
  _USERDTO._serialized_start=84
  _USERDTO._serialized_end=93
  _LOGINRESPONSEDTO._serialized_start=95
  _LOGINRESPONSEDTO._serialized_end=169
  _USER._serialized_start=172
  _USER._serialized_end=322
# @@protoc_insertion_point(module_scope)
