# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dashboard.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import app.v1.service.request_pb2 as request__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64\x61shboard.proto\x1a\rrequest.proto2\xaa\x01\n\tdashboard\x12\x38\n\x11queryTestPlanData\x12\x0f.app.v1.Request\x1a\x10.app.v1.Response\"\x00\x12\x31\n\nstatistics\x12\x0f.app.v1.Request\x1a\x10.app.v1.Response\"\x00\x12\x30\n\tworkspace\x12\x0f.app.v1.Request\x1a\x10.app.v1.Response\"\x00\x62\x06proto3')



_DASHBOARD = DESCRIPTOR.services_by_name['dashboard']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DASHBOARD._serialized_start=35
  _DASHBOARD._serialized_end=205
# @@protoc_insertion_point(module_scope)
