# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import app.v1.service.request_pb2 as request__pb2


class dashboardStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.queryTestPlanData = channel.unary_unary(
                '/dashboard/queryTestPlanData',
                request_serializer=request__pb2.Request.SerializeToString,
                response_deserializer=request__pb2.Response.FromString,
                )
        self.statistics = channel.unary_unary(
                '/dashboard/statistics',
                request_serializer=request__pb2.Request.SerializeToString,
                response_deserializer=request__pb2.Response.FromString,
                )
        self.workspace = channel.unary_unary(
                '/dashboard/workspace',
                request_serializer=request__pb2.Request.SerializeToString,
                response_deserializer=request__pb2.Response.FromString,
                )


class dashboardServicer(object):
    """Missing associated documentation comment in .proto file."""

    def queryTestPlanData(self, request, context):
        """login
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def statistics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def workspace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_dashboardServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'queryTestPlanData': grpc.unary_unary_rpc_method_handler(
                    servicer.queryTestPlanData,
                    request_deserializer=request__pb2.Request.FromString,
                    response_serializer=request__pb2.Response.SerializeToString,
            ),
            'statistics': grpc.unary_unary_rpc_method_handler(
                    servicer.statistics,
                    request_deserializer=request__pb2.Request.FromString,
                    response_serializer=request__pb2.Response.SerializeToString,
            ),
            'workspace': grpc.unary_unary_rpc_method_handler(
                    servicer.workspace,
                    request_deserializer=request__pb2.Request.FromString,
                    response_serializer=request__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dashboard', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class dashboard(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def queryTestPlanData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dashboard/queryTestPlanData',
            request__pb2.Request.SerializeToString,
            request__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def statistics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dashboard/statistics',
            request__pb2.Request.SerializeToString,
            request__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def workspace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dashboard/workspace',
            request__pb2.Request.SerializeToString,
            request__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
