FROM python:3.9-slim as builder
WORKDIR /pityUser
COPY . .
RUN python -m venv /pityUser/venv  \
    && /pityUser/venv/bin/python -m pip install --upgrade pip \
    && /pityUser/venv/bin/python -m pip install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple/ \
    && apt update -y \
    && apt upgrade -y \
    && apt install -y tzdata \
    && apt install -y wget \
    && wget https://github.com/vishnubob/wait-for-it/raw/master/wait-for-it.sh


FROM python:3.9-slim
ENV PYTHONUNBUFFERED=1
WORKDIR /pityUser
COPY . .
COPY --from=builder /pityUser/venv/ /pityUser/venv/
COPY --from=builder /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
COPY --from=builder /pityUser/wait-for-it.sh /pityUser/ops/wait-for-it.sh
RUN ln -sf /pityUser/ops/dev.env.ops /pityUser/conf/dev.env \
    && chmod +x /pityUser/ops/wait-for-it.sh

EXPOSE 10011